# NLP Practical 1 — Tokenization, Stemming, and Lemmatization

## Aim

To perform different types of tokenization using the NLTK library and apply stemming and lemmatization on a sample sentence.

## Description

Natural Language Processing begins with preprocessing text. This experiment demonstrates various tokenization techniques such as whitespace tokenization, punctuation-based tokenization, Treebank tokenization, Tweet tokenization, and Multi-Word Expression (MWE) tokenization. It also demonstrates stemming using Porter and Snowball stemmers and lemmatization using WordNet.

## Requirements

* Python 3.x
* nltk library

Install required library:
pip install nltk

Download required resources:
import nltk
nltk.download('punkt')
nltk.download('wordnet')

## Dataset / Input

Sample sentence used for demonstration:
Natural Language Processing is amazing! Let's learn NLP using Python.

## Steps

1. Import NLTK libraries.
2. Define a sample sentence.
3. Perform whitespace tokenization.
4. Perform punctuation-based tokenization.
5. Perform Treebank tokenization.
6. Perform Tweet tokenization.
7. Perform Multi-Word Expression (MWE) tokenization.
8. Apply Porter Stemmer.
9. Apply Snowball Stemmer.
10. Apply WordNet Lemmatization.

## Expected Output

* List of tokens generated by different tokenizers.
* Stemmed words using Porter and Snowball stemmers.
* Lemmatized words.

## How to Run

python practical1.py

## Conclusion

This experiment demonstrates fundamental NLP preprocessing techniques including tokenization, stemming, and lemmatization using the NLTK library.
